# Build
FROM golang:1.19-alpine AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY ./ ./

RUN go build -o /app/server.exe ./demo/server/main.go

# Deploy
FROM alpine

WORKDIR /app

COPY --from=build /app/server.exe ./server.exe

EXPOSE 5060
EXPOSE 5080
EXPOSE 8000

RUN chmod +x server.exe

RUN apk add bash

CMD [ "./server.exe" ]